### ISSUE TITLE
加载组装的html字符串，会闪退

### ISSUE THREAD

**Issue by zhujinsheng** [zhaolongs/Flutter_Fai_Webview#1]
![image](https://user-images.githubusercontent.com/16300475/62286076-95e76580-b489-11e9-8d27-e4ee0c65358e.png)
  例子数据：var htemlS2 =
      '<html><head><meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"> <style>img{max-width: 100%; width:auto; height:auto;}</style></head><body><p style="text-align:center;"> <img src="http://img01.kzj365.com/1506576517174.jpg" alt="" /><img src="http://img01.kzj365.com/1506576517663.jpg" alt="" /><img src="http://img01.kzj365.com/1506576517981.jpg" alt="" /><img src="http://img01.kzj365.com/1506576518282.jpg" alt="" /><img src="http://img01.kzj365.com/1506576519603.jpg" alt="" /><span></span></p> <div> <br /></div></body></html>';

**Comment by zhaolongs** [comment]
[1.1.0](https://pub.flutter-io.cn/packages/flutter_fai_webview) 版本修复
