### ISSUE TITLE
使用UIWebView导致app无法上架

### ISSUE THREAD

**Issue by vale8023** [zhaolongs/Flutter_Fai_Webview#16]
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

**Comment by zhaolongs** [comment]
1.1.6 版本已处理  

在项目 ios 目录下打开终端， 输入：grep -r UIWebView .，会显示出项目中所有的隐藏的UIWebView， 包括第三方framework
