### ISSUE TITLE
黑一闪动画

### ISSUE THREAD

**Issue by ixugo** [zhaolongs/Flutter_Fai_Webview#17]
下载了 demo , 打开了几个选项 , 有 "黑一闪" ,  如 [视频](http://img.golang.space/1608175597409-1608175348074.mp4)所示
不好意思 , 我不懂安卓 , 不清楚是哪里导致的

## 平台
安卓 10 , 小米 8  ( ios 没有此问题)

## flutter 版本
1.23

## 步骤
运行 demo , 点击包含网页的按钮

**Comment by mingV2019** [comment]
我也小米混合页面，web加载出来的一刹那会闪

**Comment by KevinHua** [comment]
同样的问题，黑一闪问题出现在 loading 之后，网页显示之前

**Comment by ixugo** [comment]
未解决，关闭问题。
