### ISSUE TITLE
集成之后，最简单的按url显示webview，显示不出来

### ISSUE THREAD

**Issue by CoderHln** [zhaolongs/Flutter_Fai_Webview#3]
报错内容：Trying to embed a platform view but the PrerollContext does not support embedding
Trying to embed a platform view but the PaintContext does not support embedding

**Comment by CoderHln** [comment]
已解决，在iOS工程的info.plist文件中添加键值对key=io.flutter.embedded_views_preview value=YES

**Comment by zhaolongs** [comment]
遗漏了消息回复  
[已升级到put仓库](https://pub.flutter-io.cn/packages/flutter_fai_webview)
