### ISSUE TITLE
android 弹出键盘webview会消失

### ISSUE THREAD

**Issue by punkwang** [zhaolongs/Flutter_Fai_Webview#4]
`

Widget buildView(SpotDetailState state, Dispatch dispatch, ViewService viewService) {
  return Scaffold(
    appBar: AppBar(
      title: Text('测试'),
    ),
    body: SingleChildScrollView(
      physics:BouncingScrollPhysics(),
      child: Division(
        style: StyleClass()
          ..width(ScreenUtil.getScreenW(viewService.context))
          ..height(ScreenUtil.getScreenH(viewService.context))
          ..margin(all: 10)
          ..background.color(Colors.green)
        ,
        child: FaiWebViewWidget(
          //webview 加载网页链接
          url: "http://www.google.com/",
        ),
      ),
    ),
    bottomNavigationBar: Division(
      child: Text('djfkdfsdf'),
    ),
  );
}
`

**Comment by zhaolongs** [comment]
应该是没有 fan qiang 的原因
