### ISSUE TITLE
Flutter 调用js方法怎么传参，

### ISSUE THREAD

**Issue by CoderHln** [zhaolongs/Flutter_Fai_Webview#6]
有没有相关方面的demo？感谢

**Comment by zmm2tysu** [comment]
我执行flutter packages get 就报这个错，你们是怎么down的插件啊

Git error. Command: git rev-list --max-count=1 master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

**Comment by zhaolongs** [comment]
昨天已完善了一版 Flutter 中与 JS的双向互调，可查看 说明中的的第三小节
