### ISSUE TITLE
部分老旧机型，低分辨率手机， 加载长图会闪退

### ISSUE THREAD

**Issue by ZhouHGit** [zhaolongs/Flutter_Fai_Webview#9]
`E/webview pageFinish( 6648): web view loading finish mMeasuredHeight 3117.0
I/flutter ( 6648): native_webview:code-> 401 ; message:webview 开始加载; content 
I/flutter ( 6648): native_webview callback
I/flutter ( 6648): native_webview:code-> 402 ; message:webview 加载完成; content 
I/flutter ( 6648): native_webview callback
I/flutter ( 6648): native_webview:code-> 201 ; message:测量成功V; content 3117.0
I/flutter ( 6648): native_webview callback
I/flutter ( 6648): native_webview:code-> 403 ; message:webview 日志输出; content console lineNumber:【1-->message:Uncaught ReferenceError: getAllImgSrc is not defined】
I/flutter ( 6648): native_webview callback
W/PlatformViewsController( 6648): Creating a virtual display of size: [948, 8654] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1080, 2050].
I/HwPointEventFilter( 6648): do not support AFT because of no config
E/GLConsumer( 6648): [SurfaceTexture-0-6648-0] bindTextureImage: error binding external image: 0x501
E/flutter ( 6648): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.RuntimeException: Error during updateTexImage (see logcat for details)
E/flutter ( 6648): 	at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
E/flutter ( 6648): 	at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:240)
E/flutter ( 6648): 
`
华为BND-AL10

**Comment by zhaolongs** [comment]
1.1.1版本中已处理

**Comment by parcool** [comment]
就[加载混合页面](https://github.com/zhaolongs/Flutter_Fai_Webview#23-%E5%8A%A0%E8%BD%BD%E6%B7%B7%E5%90%88%E9%A1%B5%E9%9D%A2)直接复制粘贴，然后运行等会儿就闪退。。。
小米10 pro。

能不能限制webview的高度的最大为内容视图的高度？当滑到底部后把滑动事件交个webview，webview回到顶部后又把事件换给外面的ScrollView？

**Comment by zhaolongs** [comment]
这个方案可以有  等1-2天处理下

**Comment by parcool** [comment]
@zhaolongs 等你哦老哥
